### ISSUE TITLE
Error when running `apache2-license-checker`

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/apache2-license-checker#10]
Tried running against https://github.com/bbc/simorgh.

```
$ apache2-license-checker
Checked for local license-exceptions.json; but no file was found.
/Users/ashtoc03/Sites/bbc/simorgh/node_modules/@bbc/apache2-license-checker/scripts/check-licenses.js:16
  return exceptions[key] || exceptions[anyVersionKey]
                   ^

TypeError: Cannot read property 'abab@2.0.0' of undefined
    at inExceptionList (/Users/ashtoc03/Sites/bbc/simorgh/node_modules/@bbc/apache2-license-checker/scripts/check-licenses.js:16:20)
    at Object.keys.forEach (/Users/ashtoc03/Sites/bbc/simorgh/node_modules/@bbc/apache2-license-checker/scripts/check-licenses.js:34:25)
    at Array.forEach (<anonymous>)
    at checkLicenses (/Users/ashtoc03/Sites/bbc/simorgh/node_modules/@bbc/apache2-license-checker/scripts/check-licenses.js:28:25)
    at ChildProcess.command.on (/Users/ashtoc03/Sites/bbc/simorgh/node_modules/@bbc/apache2-license-checker/run.js:23:3)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
```

**Comment by johnbeech** [comment]
Thanks for the report, will look into that this morning - what directory / project did you run in it?

**Comment by ChrisBAshton** [comment]
In the root. Thanks

**Comment by johnbeech** [comment]
@ChrisBAshton checked out the simorgh repo, installed the license checker, ran `npm install`, and managed to get this output:

```
[MAC: simorgh] npm run check-licenses

> simorgh@0.0.1 check-licenses /Users/beechj01/workspace/simorgh
> apache2-license-checker

Checked for local license-exceptions.json; but no file was found.
Acceptable project licenses (uses):
  (BSD-2-Clause OR MIT OR Apache-2.0) (2)
  (BSD-3-Clause OR GPL-2.0) (1)
  (GPL-2.0 OR MIT) (1)
  (MIT AND BSD-3-Clause) (1)
  (MIT AND Zlib) (1)
  (MIT OR Apache-2.0) (1)
  (MIT OR GPL-3.0) (1)
  (MIT OR WTFPL) (1)
  (WTFPL OR MIT) (2)
  AFLv2.1,BSD (1)
  Apache License, Version 2.0 (2)
  Apache-2.0 (75)
  BSD (4)
  BSD* (13)
  BSD-2-Clause (33)
  BSD-3-Clause (50)
  CC-BY-3.0 (1)
  CC-BY-4.0 (2)
  CC0-1.0 (2)
  ISC (107)
  MIT (1592)
  MIT* (9)
  MPL-2.0 (1)
  Public Domain (1)
  Unlicense (1)
  WTFPL (2) 

Problems with the licenses for these dependencies:
  atob@2.1.2
    License:     (MIT OR Apache-2.0)
    Repository:  git://git.coolaj86.com/coolaj86/atob.js
    Publisher:   AJ ONeal
    Url:         https://coolaj86.com

  axe-core@3.0.0-beta.2
    License:     MPL-2.0
    Repository:  https://github.com/dequelabs/axe-core
    Publisher:   undefined
    Url:         undefined

  caniuse-db@1.0.30000938
    License:     CC-BY-4.0
    Repository:  https://github.com/Fyrd/caniuse
    Publisher:   Alexis Deveria
    Url:         undefined

  caniuse-lite@1.0.30000928
    License:     CC-BY-4.0
    Repository:  https://github.com/ben-eb/caniuse-lite
    Publisher:   Ben Briggs
    Url:         http://beneb.info

  expand-template@2.0.3
    License:     (MIT OR WTFPL)
    Repository:  https://github.com/ralphtheninja/expand-template
    Publisher:   LM
    Url:         undefined

  jszip@3.1.5
    License:     (MIT OR GPL-3.0)
    Repository:  https://github.com/Stuk/jszip
    Publisher:   Stuart Knightley
    Url:         undefined

  node-forge@0.7.5
    License:     (BSD-3-Clause OR GPL-2.0)
    Repository:  https://github.com/digitalbazaar/forge
    Publisher:   Digital Bazaar, Inc.
    Url:         http://digitalbazaar.com/

  pako@1.0.7
    License:     (MIT AND Zlib)
    Repository:  https://github.com/nodeca/pako
    Publisher:   undefined
    Url:         undefined

  sha.js@2.4.11
    License:     (MIT AND BSD-3-Clause)
    Repository:  https://github.com/crypto-browserify/sha.js
    Publisher:   Dominic Tarr
    Url:         dominictarr.com

  ua-parser-js@0.7.19
    License:     (GPL-2.0 OR MIT)
    Repository:  https://github.com/faisalman/ua-parser-js
    Publisher:   Faisal Salman
    Url:         http://faisalman.com
 

Licenses not ok Licensed (1897) Exceptions (0) Problems (10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simorgh@0.0.1 check-licenses: `apache2-license-checker`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simorgh@0.0.1 check-licenses script.
```

Hope that's what you were after :)

**Comment by johnbeech** [comment]
Also, side note... we were considering making the whitelist a per-project configuration as well, and having a set of defaults, but I need to talk with David, Steph and Richard T further since choice of acceptable licenses is under their purview.

**Comment by ChrisBAshton** [comment]
Confirmed it works - not sure what went wrong! Thanks
